##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.24.1] date: [Fri Aug 18 13:20:33 MSK 2017]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = STM32FX_DISCOVERY

#TEST_CATALOG = test_F4
TEST_CATALOG = test_F0


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O2


#######################################
# paths
#######################################
# source path
SOURCES_DIR =  
SOURCES_DIR += Application 
#SOURCES_DIR += . 
SOURCES_DIR += hal
SOURCES_DIR += hal/ral
SOURCES_DIR += $(TEST_CATALOG)
ifeq ($(TEST_CATALOG), test_F4)
SOURCES_DIR += STM32F4_files 
SOURCES_DIR += STM32F4_files/CMSIS
endif
ifeq ($(TEST_CATALOG), test_F0)
SOURCES_DIR += STM32F0_files 
SOURCES_DIR += STM32F0_files/CMSIS
endif





# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
ifeq ($(TEST_CATALOG), test_F4)
C_SOURCES = STM32F4_files/system_stm32f4xx.c 
endif
ifeq ($(TEST_CATALOG), test_F0)
C_SOURCES = STM32F0_files/system_stm32f0xx.c 
endif
 
# C++ sourses
CPP_SOURCES = 
CPP_SOURCES += $(TEST_CATALOG)/main.cpp 


# ASM sources
ifeq ($(TEST_CATALOG), test_F4)
ASM_SOURCES = STM32F4_files/startup_stm32f405xx.s
endif
ifeq ($(TEST_CATALOG), test_F0)
ASM_SOURCES = STM32F0_files/startup_stm32f030x6.s
endif


######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
#PREFIX = /home/slonegd/Code/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-
#PREFIX = /home/dvk/code/gcc-arm-none-eabi-6-2017-q1-update/bin/arm-none-eabi-
#PREFIX = /home/peltikhin/code/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-

CPP = $(PREFIX)g++
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
AR = $(PREFIX)ar
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
ifeq ($(TEST_CATALOG), test_F4)
CPU = -mcpu=cortex-m4
endif
ifeq ($(TEST_CATALOG), test_F0)
CPU = -mcpu=cortex-m0
endif

# fpu
ifeq ($(TEST_CATALOG), test_F4)
FPU = -mfpu=fpv4-sp-d16
endif
# NONE for Cortex-M0/M0+/M3

# float-abi
ifeq ($(TEST_CATALOG), test_F4)
FLOAT-ABI = -mfloat-abi=hard
endif

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
ifeq ($(TEST_CATALOG), test_F4)
C_DEFS = -DSTM32F405xx
endif
ifeq ($(TEST_CATALOG), test_F0)
C_DEFS = -DSTM32F030x6
endif


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  
C_INCLUDES += -I.
C_INCLUDES += -I$(TEST_CATALOG)
C_INCLUDES += -Ihal
C_INCLUDES += -Ihal/ral
ifeq ($(TEST_CATALOG), test_F4)
C_INCLUDES += -ISTM32F4_files 
C_INCLUDES += -ISTM32F4_files/CMSIS 
endif
ifeq ($(TEST_CATALOG), test_F0)
C_INCLUDES += -ISTM32F0_files 
C_INCLUDES += -ISTM32F0_files/CMSIS 
endif


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections 

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2 
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
ifeq ($(TEST_CATALOG), test_F4)
LDSCRIPT = STM32F4_files/STM32F405RGTx_FLASH.ld
endif
ifeq ($(TEST_CATALOG), test_F0)
LDSCRIPT = STM32F0_files/STM32F030K6Tx_FLASH.ld
endif

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -std=c99 -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR) 
	$(CPP) -c $(CFLAGS) -std=c++1y -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)

flash_stlink:
	/home/dvk/code/stlink/build/Release/st-flash write $(BUILD_DIR)/$(TARGET).bin 0x8000000
#	/home/slonegd/Code/stlink/build/Release/st-flash write $(BUILD_DIR)/$(TARGET).bin 0x8000000
#	st-flash write $(BUILD_DIR)/$(TARGET).bin 0x8000000

util:
	/home/dvk/code/stlink/build/Release/src/gdbserver/st-util
#	/home/slonegd/Code/stlink/build/Release/src/gdbserver/st-util

debug: clean all flash_stlink util
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

# *** EOF ***